source "$(dirname "$0")/_classpath.sh"
cd "$ROOT"
build_host_classes
{
cat <<'HDR'
# Parameter reference

Generated by `scripts/config.sh DIR params-md` from the live `ParamRegistry` and **checked by a test**
(`docs: PARAMETERS.md matches the registry`). Regenerate it with `scripts/gen_param_docs.sh` when you add or change a parameter.

Categories: **FIXED_DERIVED** never adjusted by tools - **HARDWARE_CAL** set from measurements - **CONTROLLER** gains/weights -
**BEHAVIOR** tolerances/timings/thresholds - **SAFETY** caps (file edits may only tighten; mechanical limits are measured-only) -
**INTERLOCK** master enables that require their dependencies to be explicitly calibrated.
"placeholder default" means the compiled value is NOT hardware data; the validator refuses interlocks until it has been replaced by an explicit value.

HDR
java -cp "$OUT:$CP" org.firstinspires.ftc.teamcode.tuning.cli.ConfigTool /tmp/x params-md
} > docs/PARAMETERS.md
